version: '2.2'

services:
  db:
    image: mysql:5.7
    ports:
      - "3007:3306"
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'apassword'
      MYSQL_ROOT_PASSWORD: 'apassword'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/frexcodesafio
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db: 
        condition: service_healthy

    