version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_HOST: 'host.docker.internal'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'apassword'
      MYSQL_ROOT_PASSWORD: 'apassword'
      
     
    
  web:
    build: .
    command: python manage.py runserver 
    volumes:
      - .:/frexcodesafio
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

    