version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'frexco_api'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'slipknot00'
       MYSQL_ROOT_PASSWORD: 'slipknot00'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/frexcodesafio
    ports:
      - "8000:8000"
    depends_on:
      - db